### ISSUE TITLE
Error TensorFlow Library

### ISSUE THREAD

**Issue by bartlombardi** [jjasonn0717/Distributed-Mnist#1]
Hi, some TensorFlow features was changed, for example: softmax_classifier is no more usable. 
So your code isn't runnable and I wonder how can I fix the code.
Can you help me ?
Thanks.
 
This is run-time error:

```
WARNING:tensorflow:From /usr/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/models.py:175 in logistic_regression.: softmax_classifier (from tensorflow.contrib.learn.python.learn.ops.losses_ops) is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Use tf.contrib.losses.softmax_cross_entropy and explicit logits computation.
WARNING:tensorflow:From distributed_mnist.py:212 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
Traceback (most recent call last):
  File "distributed_mnist.py", line 321, in <module>
    tf.app.run()
  File "/usr/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "distributed_mnist.py", line 228, in main
    clip_gradients=1)
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py", line 247, in optimize_loss
    "Unknown type %s for clip_gradients" % type(clip_gradients))
ValueError: Unknown type <class 'int'> for clip_gradients
```

**Comment by HudsonHuang** [comment]
@bartlombardi you can just set clip_gradients=None to get the code run.
